### ISSUE TITLE
SoL console does not accept keyboard input

### ISSUE THREAD

**Issue by webD97** [open-amt-cloud-toolkit/sample-web-ui#2013] opened 2024-07-15 12:34 UTC
**Describe the bug** 🪲
We are currently evaluating the following use case of the toolkit using the sample ui: We have multiple Linux servers with AMT configured in admin control mode where we want to use SoL to login to the servers if sshd is not available for whatever reason. SoL is enabled, user consent is 'none' and the Linux server is running serial-getty@ttyS1 to provide a login dialog on the serial port. Data sent from the server to the frontend is shown properly:

![grafik](https://github.com/user-attachments/assets/8eb87ee2-2961-46ab-8904-6fa3d3d45e7d)

When typing any characters within the console (e.g. to enter a user name), no data is sent to the remote server. This can also be observed in the browser's dev tools: no messages are being sent when typing. If the server sends stuff to the serial port, the websocket shows data being transferred and the frontend renders it properly.

However: If you paste the text from the clipboard via the browser's context menu, the data is sent properly and the server reacts to it. So to properly use the terminal, you currently need to paste everything into it which is quite inconvenient.

**To Reproduce** 🪜

1. Configure a Linux server in ACM and connect it to the OACT instance
2. Open the device in sample-web-ui and start a SoL session
3. (re)start serial-getty@ttyS1.service on the server
4. sample-web-ui will show a login prompt
5. Type something in the console -> nothing will happen
6. Paste a short string from the clipboard -> it will show up in the console

**Expected behavior**
Data is sent to the server when typing.

**Screenshots** 🖼️
n.a.

**Browser Information (please complete the following information):** 🖥️

- OS: Windows 10 22H2
- Browser and Version: Firefox 128.0, Edge 126.0.2592.102

**Server Side Deployment (please complete the following information):** ⛈️

- Deployment Type: k8s
- Node Version: n.a.
- Component & Version: sample-web-ui v3.10.1

**Additional context**
AMT versions in use are 16.1.27 and 15.0.45.

**Comment by nekator** [comment] 2024-09-19 12:01
I´m facing the same error. The error appears in sample-web-ui and console app. So it must be a problem with the angular component. React SOL Component works without problems.

**Comment by graikhel-intel** [comment] 2024-09-26 03:52
This should be resolved in the latest sample-web-ui release https://github.com/open-amt-cloud-toolkit/sample-web-ui/releases/tag/v3.21.1. Pull the latest image and let us know if the issue is resolved.

We plan to release another alpha version of Console soon which will include the SOL fix.

**Comment by webD97** [comment] 2024-09-26 06:11
I just updated and can confirm that it works now. Thank you very much! Maybe @nekator wants to test it too, otherwise feel free to close this issue :)

**Comment by nekator** [comment] 2024-09-26 06:15
Tested it right now. Input works as expected. Thanks for the fix 👍

**Closed** 2024-09-26 14:18 UTC
Labels: bug, P1
