### ISSUE TITLE
[DMC] Add WSMAN browser to Device Details Page

### ISSUE THREAD

**Issue by graikhel-intel** [open-amt-cloud-toolkit/sample-web-ui#1877] opened 2024-05-14 18:14 UTC
As a console user, I want a way to Get AMT, IPS and CIM WSMAN class instances from Device Details Page.

### Acceptance Criteria
-  [x] Ability to search through all the query-able WSMAN classes.
-  [x] Select the class and hit GET details button to pull WSMAN class information.

**Comment by rsdmike** [comment] 2024-07-01 22:27
Closing as duplicate of #1132

**Closed by rsdmike** 2024-07-01 22:27 UTC
